# Martin Tile Server Configuration
unstable: true
keep_alive: 75
listen_addresses: "0.0.0.0:3000"

sources:
  # This tells martin to look for any .pmtiles files in your data folder
  pmtiles:
    paths:
      - /home/ovisopa/osm-station/data
